# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import wazimap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyYouth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_level', models.CharField(max_length=15)),
                ('geo_code', models.CharField(max_length=10)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('long_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('year', models.IntegerField(db_index=True, null=True)),
                ('square_kms', models.FloatField(null=True)),
                ('parent_level', models.CharField(max_length=15, null=True)),
                ('parent_code', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'wazimap_geography_youth',
            },
            bases=(models.Model, wazimap.models.GeoMixin),
        ),
    ]
